version: "3.8"
services:
  radius:
    hostname: radius
    image: nicolonsky-freeradius-prod
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Zurich
    restart: always
    ports:
      - "1812-1813:1812-1813/udp"